In [13]:
import numpy as np

In [14]:
#creating array with arrange function of numpy
a=np.arange(15)  #single dimension
a=np.arange(15).reshape(3,5) #multidimension

In [15]:
#size of array
a.size

15

In [18]:
#dimension of array
a.ndim

2

In [19]:
#data type of array
a.dtype

dtype('int32')

In [20]:
#creating array from a iterator
list_b=[1,2,3,4,5,6,7,8,9]
n=np.array(list_b).reshape(3,3)

In [16]:
#crearing multi-dimension array from a iterator
b=np.array([(1,5,2,3),(4,5,6)])

C:\Users\HP\AppData\Local\Temp/ipykernel_4968/659809734.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([(1,5,2,3),(4,5,6)])


In [17]:
#dtype can also be specified
c=np.array([ [1,2],[3,4] ],dtype=complex)

In [18]:
#array of zeros
zeros=np.zeros( (3,4))

In [19]:
#array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#custom range
cd=np.arange(0,2,0.3)

Basic operations

In [21]:
a=np.array([20,30,40,50])
b=np.arange(4)  #array([0,1,2,3])
c=a-b #output:array([20,29,38,47])
print(c)

[20 29 38 47]


In [28]:
b**2 #output:array([0,1,2,3])
10*np.sin(a)   #output:array([9.12945251,-9.88031624,7.4511316,-2.62374854])
a<35 #output:array([True,True,False,False])

array([ True,  True, False, False])

In [29]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
prod1=A*B  #elementwise product
prod2=A@B  #matrix product
prod=A.dot(B) #another matrix product

In [ ]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3 #multiplies to each element
b+=a #adds to each elements


In [22]:
arr3=np.random.randint(1,10,(4,5))

array([[3, 7, 7, 9, 5],
       [2, 6, 7, 3, 5],
       [9, 5, 1, 8, 3],
       [5, 4, 7, 5, 5]])

In [25]:
arr=np.random.randint(1,10,(4,5))

In [24]:
arr.sum()

100

In [26]:
arr.min()

2

In [28]:
arr.max()

9

In [36]:
arr1=np.arange(11,20).reshape(3,3)

In [37]:
arr1[1]

array([14, 15, 16])

In [38]:
arr1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [39]:
arr1[1,2]

16

In [46]:
arr2=np.arange(1,21).reshape(4,5)

In [47]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [49]:
arr2[3,3]

19

In [52]:
arr2[2,3:5]

array([14, 15])

In [66]:
arr2[1:4:1,1]

array([ 7, 12, 17])

In [68]:
arr2.diagonal()

array([ 1,  7, 13, 19])

In [73]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [74]:
np.ceil(arr2)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [78]:
#stacking vertically== number of column should be same
arr4=np.arange(1,7).reshape(2,3)
arr5=np.arange(8,14).reshape(2,3)

In [79]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
arr5

array([[ 8,  9, 10],
       [11, 12, 13]])

In [80]:
np.vstack((arr4,arr5))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [81]:
np.hstack((arr4,arr5))

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [83]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
np.hsplit(arr4,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [86]:
np.vsplit(arr4,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [87]:
arr4.T  #transpose array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
np.eye(3)      #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])